  "end of file", "blank", "syntax error", "<", "cw", "ccw", "(",
 ")", "*", "+", "-", "/", "%", "end of line or ;", "^", "!", "&&",
 "||", ",", ":", "[", "]", "{", "}", ".", "[]", "`", "'", "=",
 ":=", "+=", "-=", "*=", "/=", "%=", "&", "number", "identifier",
 "label", "LaTeX", "string", "#", "$ argument", ".PS", "end of file or .PE",
 "ht", "wid", "rad", "diam", "thick", "scaled", "from", "to",
 "at", "with", "by", "then", "continue", "chop", "same", "of",
 "the", "way", "between", "and", "Here", "th", "last", "fill",
 ".x", ".y", "print", "copy", "reset", "exec", "sh", "command",
 "define", "undef", "rand", "if", "else", "for", "do", "end of for {...} contents",
 "sprintf", "compass corner: .n .ne .center .end etc", ".ne",
 ".se", ".nw", ".sw", ".n", ".s", ".e", ".w", "start", "end",
 ".c", "logical operator", "==", "!=", ">=", "<=", ">", "attribute .ht .wid etc",
 ".ht", ".wid", ".rad", ".diam", ".thick", ".len", "function (1 arg)",
 "abs", "acos", "asin", "cos", "exp", "expe", "int", "log", "loge",
 "sign", "sin", "sqrt", "tan", "floor", "function (2 args)", "atan2",
 "max", "min", "pmod", "line type: dotted etc", "solid", "dotted",
 "dashed", "invisible", "color spec: colored outlined shaded",
 "coloured", "outlined", "shaded", "text position: ljust rjust above below center",
 "center", "ljust", "rjust", "above", "below", "arrowhead parameter: <- -> <->",
 "<-", "->", "<->", "direction: up down right left", "up", "down",
 "right", "left", "drawn object: box circle etc", "box", "circle",
 "ellipse", "arc", "line", "arrow", "move", "spline", "environmental variable",
 "arcrad", "arrowht", "arrowwid", "boxht", "boxrad", "boxwid",
 "circlerad", "dashwid", "ellipseht", "ellipsewid", "lineht",
 "linewid", "moveht", "movewid", "textht", "textoffset", "textwid",
 "arrowhead", "fillval", "linethick", "maxpsht", "maxpswid", "scale"

